apply plugin: "com.android.application"

android {
    compileSdk 35
    namespace "com.sample.app"
    defaultConfig {
        applicationId "com.sample.app"
        minSdkVersion 24
        targetSdkVersion 34
    }
    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "password"
            keyAlias "upload"
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
    splits {
        abi {
            reset()
            include "arm64-v8a", "armeabi-v7a", "x86"
        }
    }
    packagingOptions {
        jniLibs {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86"
        }
    }
}
